import { pgSchema, uuid, text, timestamp, jsonb, integer, bigint, boolean } from 'drizzle-orm/pg-core';

export const vistosSchema = pgSchema('vistos');

// 1. Tabela visa_info
export const visaInfo = vistosSchema.table('visa_info', {
  id: uuid('id').primaryKey().defaultRandom(),
  country: text('country').notNull(),
  countryCode: text('country_code').notNull(),
  flagEmoji: text('flag_emoji'),
  generalInfo: jsonb('general_info'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  region: text('region'),
  officialVisaLink: text('official_visa_link'),
  visaTypes: jsonb('visa_types'),
  requiredDocuments: jsonb('required_documents'),
  processSteps: jsonb('process_steps'),
  approvalTips: jsonb('approval_tips'),
  healthInfo: jsonb('health_info'),
  securityInfo: jsonb('security_info'),
  lastVerified: timestamp('last_verified', { withTimezone: true }),
  dataSource: text('data_source'),
  slug: text('slug'),
  automationStatus: text('automation_status'),
  priorityLevel: integer('priority_level'),
  metaDescription: text('meta_description'),
  ogImageUrl: text('og_image_url'),
  capital: text('capital'),
  currency: text('currency'),
  embassyAddress: text('embassy_address'),
  continent: text('continent'),
  timezone: text('timezone'),
  population: bigint('population', { mode: 'number' }),
  isVisaExempt: boolean('is_visa_exempt'),
  visaOnArrival: boolean('visa_on_arrival'),
  eVisaAvailable: boolean('e_visa_available'),
  travelInsuranceRequired: boolean('travel_insurance_required'),
  financialProofRequired: boolean('financial_proof_required'),
  allowedStayDays: integer('allowed_stay_days'),
  minBankBalanceUsd: integer('min_bank_balance_usd'),
  processingTimeMinDays: integer('processing_time_min_days'),
  processingTimeMaxDays: integer('processing_time_max_days'),
  officialLanguage: text('official_language'),
  introText: text('intro_text'),
  popularCities: text('popular_cities').array(),
  faqCustom: jsonb('faq_custom'),
  bestTimeToVisit: jsonb('best_time_to_visit'),
  relatedCountries: text('related_countries').array(),
  consulateBookingUrl: text('consulate_booking_url'),
  drivingLicenseAccepted: boolean('driving_license_accepted'),
});

// 2. Tabela applications
export const applications = vistosSchema.table('applications', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id'),
  destinationCountry: text('destination_country').notNull(),
  countryCode: text('country_code'),
  visaType: text('visa_type').notNull(),
  status: text('status').default('draft'),
  personalInfo: jsonb('personal_info'),
  travelInfo: jsonb('travel_info'),
  documents: jsonb('documents').default('[]'),
  notes: text('notes'),
  adminNotes: text('admin_notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  submittedAt: timestamp('submitted_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

// 3. Tabela payments
export const payments = vistosSchema.table('payments', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id'),
  userId: uuid('user_id'),
  amount: integer('amount').notNull(),
  currency: text('currency').notNull(),
  status: text('status').notNull().default('pending'),
  transactionId: text('transaction_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  metadata: jsonb('metadata'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// 4. Tabela blog_posts
export const blogPosts = vistosSchema.table('blog_posts', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').notNull(),
  excerpt: text('excerpt'),
  content: text('content').notNull(),
  coverImage: text('cover_image'),
  authorId: uuid('author_id'),
  category: text('category'),
  tags: text('tags').array(),
  published: boolean('published').default(false),
  views: integer('views').default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  seoTitle: text('seo_title'),
  seoDescription: text('seo_description'),
  canonicalUrl: text('canonical_url'),
  readingTime: integer('reading_time'),
  ogTitle: text('og_title'),
  ogDescription: text('og_description'),
  ogImage: text('og_image'),
  ogImageAlt: text('og_image_alt'),
  featuredImageAlt: text('featured_image_alt'),
  schemaType: text('schema_type').default('Article'),
  isFeatured: boolean('is_featured').default(false),
  contentStatus: text('content_status').default('draft'),
  relatedPosts: text('related_posts').array(),
  ctaSafetrip: boolean('cta_safetrip').default(false),
  country: text('country'),
});
