export const APPWRITE_DATABASE_ID = 'noro_db';

export const APPWRITE_COLLECTIONS = {
  TENANTS: 'tenants',
  USER_TENANTS: 'user_tenants',
  CLIENTES: 'noro_clientes',
  LEADS: 'noro_leads',
  PEDIDOS: 'noro_pedidos',
  PEDIDOS_ITENS: 'noro_pedidos_itens',
  SITES: 'sites',
  FIN_TRANSACOES: 'fin_transacoes',
  FIN_DUPLICATAS_RECEBER: 'fin_duplicatas_receber',
  FIN_DUPLICATAS_PAGAR: 'fin_duplicatas_pagar',
  FIN_CONTAS_BANCARIAS: 'fin_contas_bancarias',
  FIN_COMISSOES: 'fin_comissoes',
  VISA_COUNTRIES: 'visa_countries',
  VISA_REQUIREMENTS: 'visa_requirements',
  AI_ROTEIROS: 'noro_ai_roteiros',
  AI_ARTIGOS: 'noro_ai_artigos',
  MARKETING_SOCIAL_ACCOUNTS: 'noro_marketing_social_accounts',
  BILLING_PLANS: 'billing_plans',
  BILLING_SUBSCRIPTIONS: 'billing_subscriptions',
  BILLING_INVOICES: 'billing_invoices',
  BILLING_TRANSACTIONS: 'billing_transactions',
  BILLING_PAYMENT_METHODS: 'billing_payment_methods',
  CP_PLANS: 'cp_plans',
  CP_PLAN_FEATURES: 'cp_plan_features',
  CP_SUBSCRIPTIONS: 'cp_subscriptions',
  CP_DOMAINS: 'cp_domains',
  CP_LEADS: 'cp_leads',
  CP_CONTACTS: 'cp_contacts',
  CP_LEAD_STAGES: 'cp_lead_stages',
  CP_LEAD_ACTIVITY: 'cp_lead_activity',
  CP_TASKS: 'cp_tasks',
  CP_NOTES: 'cp_notes',
  CP_CONTROL_PLANE_USERS: 'cp_control_plane_users',
  CP_USER_ACTIVITIES: 'cp_user_activities',
  CP_CONFIG: 'cp_config',
  CP_SETTINGS: 'cp_settings',
  CP_MODULES_REGISTRY: 'cp_modules_registry',
  CP_TENANT_MODULES: 'cp_tenant_modules',
  CP_TENANT_SETTINGS: 'cp_tenant_settings',
  CP_BILLING_EVENTS: 'cp_billing_events',
  CP_SUBSCRIPTION_ADDONS: 'cp_subscription_addons',
  CP_SUBSCRIPTION_ADDON_ITEMS: 'cp_subscription_addon_items',
  CP_USAGE_COUNTERS: 'cp_usage_counters',
  CP_API_KEYS: 'cp_api_keys',
  CP_API_KEY_LOGS: 'cp_api_key_logs',
  CP_WEBHOOKS: 'cp_webhooks',
  CP_WEBHOOK_LOGS: 'cp_webhook_logs',
  CP_STRIPE_WEBHOOK_LOGS: 'cp_stripe_webhook_logs',
  CP_SUPPORT_TICKETS: 'cp_support_tickets',
  CP_SUPPORT_MESSAGES: 'cp_support_messages',
  CP_SUPPORT_EVENTS: 'cp_support_events',
  CP_SUPPORT_SLA: 'cp_support_sla',
  CP_SECURITY_AUDIT_LOG: 'cp_security_audit_log',
  CP_SECURITY_ALERTS: 'cp_security_alerts',
  CP_SYSTEM_EVENTS: 'cp_system_events',
  CP_LEDGER_ACCOUNTS: 'cp_ledger_accounts',
  CP_LEDGER_ENTRIES: 'cp_ledger_entries',
  CP_PRODUTOS_PRECOS: 'cp_produtos_precos',
} as const;

export type AppwriteCollectionId =
  (typeof APPWRITE_COLLECTIONS)[keyof typeof APPWRITE_COLLECTIONS];
